reader: pymupdf   
enable_ocr: false
table_extractor: camelot
page_ranges: "all"
detect_columns: true
strip_headers_footers: true
normalize_affiliations: true
reference_style: "auto"
emit_base64_figures: false
emit_tables_as_html: true
timeout_sec: 120
